apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry-config
  namespace: sentry-system
  labels:
    app.kubernetes.io/name: sentry
    app.kubernetes.io/component: config
data:
  sentry.yaml: |
    # Sentry configuration file
    monitor:
      # Repository A configuration (GitHub)
      repo_a:
        type: "github"
        url: "https://github.com/NVIDIA-AI-Blueprints/rag"
        branch: "main"
        token: "${GITHUB_TOKEN}"  # Environment variable from Secret
      
      # Repository B configuration (GitLab)  
      repo_b:
        type: "gitlab"
        url: "https://gitlab-master.nvidia.com/cloud-service-qa/Blueprint/blueprint-github-test"
        branch: "main"
        token: "${GITLAB_TOKEN}"  # Environment variable from Secret
      
      # Polling configuration
      poll:
        interval: 30  # Poll interval in seconds
        timeout: 10   # Request timeout in seconds

    # Deployment configuration
    deploy:
      namespace: "tekton-pipelines"  # Kubernetes namespace
      tmp_dir: "/tmp/sentry"         # Temporary directory
      cleanup: true                  # Auto cleanup temporary files
---
