# Default values for sentry
# This is a YAML-formatted file

# Application metadata
nameOverride: ""
fullnameOverride: ""

# Image configuration
image:
  repository: localhost:5000/sentry
  pullPolicy: IfNotPresent
  tag: "1.0.0"

# Image pull secrets
imagePullSecrets: []

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Replica count
replicaCount: 1

# Namespace configuration
namespace:
  create: true
  name: sentry-system

# Application configuration
config:
  # Polling interval in seconds (minimum 60)
  polling_interval: 60
  
  # Global group configurations
  groups:
    ai-blueprints:
      execution_strategy: "parallel"  # parallel | sequential
      max_parallel: 3
      continue_on_error: true
      global_timeout: 900  # 15 minutes
  
  # Repository configurations
  repositories:
    - name: "rag-project"
      group: "ai-blueprints"  # Optional group assignment
      monitor:
        repo_url: "https://github.com/johnnynv/rag"
        branches: ["main", "dev"]  # Multiple branches supported
        repo_type: "github"
        auth:
          username: "placeholder_github_username"
          token: "${GITHUB_TOKEN}"
      deploy:
        qa_repo_url: "https://gitlab-master.nvidia.com/cloud-service-qa/Blueprint/blueprint-github-test"
        qa_repo_branch: "rag-tekton-workflow"
        repo_type: "gitlab"
        project_name: "rag"
        commands:
          - "cd .tekton/rag && export TMPDIR=/tmp/sentry && bash scripts/container-deployment-pipeline-onclick.sh"
        auth:
          username: "placeholder_gitlab_username"
          token: "${GITLAB_TOKEN}"

    - name: "chatbot-project"
      group: "ai-blueprints"
      monitor:
        repo_url: "https://github.com/johnnynv/rag"
        branches: ["main"]
        repo_type: "github"
        auth:
          username: "placeholder_github_username"
          token: "${GITHUB_TOKEN}"
      deploy:
        qa_repo_url: "https://gitlab-master.nvidia.com/cloud-service-qa/Blueprint/blueprint-github-test"
        qa_repo_branch: "rag-tekton-workflow"
        repo_type: "gitlab"
        project_name: "chatbot"
        commands:
          - "cd .tekton/chatbot && export TMPDIR=/tmp/sentry && bash scripts/container-deployment-pipeline-onclick.sh"
        auth:
          username: "placeholder_gitlab_username"
          token: "${GITLAB_TOKEN}"

  # Global settings
  global:
    tmp_dir: "/tmp/sentry"
    cleanup: true
    timeout: 300

  # API credentials (will be set via command line parameters)
  github:
    username: "johnnynv"  # Default GitHub username, override with --set config.github.username=your_username
  gitlab:
    username: "johnnyj"   # Default GitLab username, override with --set config.gitlab.username=your_username

# Secret configuration
secrets:
  # GitHub token (base64 encoded)
  githubToken: ""
  # GitLab token (base64 encoded)
  gitlabToken: ""
  # Create secret from values
  create: true
  # Use existing secret
  existingSecret: ""

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true
  # Additional rules
  additionalRules: []

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

# Health checks
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 3
  command:
    - sentry
    - -action=validate
    - -config=/etc/sentry/sentry.yaml

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 1
  command:
    - sentry
    - -action=validate
    - -config=/etc/sentry/sentry.yaml

# Additional environment variables
env: []
# - name: CUSTOM_VAR
#   value: "custom_value"

# Additional volumes
extraVolumes: []
# - name: extra-volume
#   emptyDir: {}

# Additional volume mounts
extraVolumeMounts: []
# - name: extra-volume
#   mountPath: /extra-path

# Command line arguments
args:
  - "-action=watch"
  - "-verbose"
  - "-config=/etc/sentry/sentry.yaml"

# Enable verbose logging
verbose: true

# Termination grace period
terminationGracePeriodSeconds: 30
