apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentry.configMapName" . }}
  namespace: {{ include "sentry.namespace" . }}
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  sentry.yaml: |
    # Sentry configuration file
    monitor:
      {{- toYaml .Values.config.monitor | nindent 6 }}
    
    # Deployment configuration
    deploy:
      {{- toYaml .Values.config.deploy | nindent 6 }}
