{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "sentry.namespace" . }}
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}
